### ISSUE TITLE
复现train.py的一个报错。

### ISSUE THREAD

**Issue by timohaha** [ouyanghuiyu/yolo-face-with-landmark#1]
`
Saving labels to /home/ps/superb/yolo-face-with-landmark/datas/yololandmark_wider_train.npy for faster future loading
Image sizes 320 - 640 train, 640 test
Using 8 dataloader workers
Starting training for 250 epochs...

     Epoch   gpu_mem      GIoU       obj       cls      land     total   targets  img_size        lr
  0%|                     | 0/805 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 365, in <module>
    train(hyp)  # train normally
  File "train.py", line 265, in train
    loss, loss_items = compute_loss(pred, targets, model,point_number=hyp['point_num'])
  File "/home/ps/zhouyizhi/yolo-face-with-landmark/utils/utils.py", line 238, in compute_loss
    tcls, tbox, tpoint ,indices, anchors = build_targets(p, targets, model,point_number=point_number)  # targets
  File "/home/ps/zhouyizhi/yolo-face-with-landmark/utils/utils.py", line 342, in build_targets
    no_train_index = torch.where(targets == -1 )
TypeError: where() missing 2 required positional argument: "input", "other"
`
请问下作者，这个错误该如何解决。

**Comment by timohaha** [comment]
build_targets函数的参数好像少了一个？

**Comment by DayBreak-u** [comment]
@timohaha 是不是因为torch版本的问题，我是1.4.0

**Comment by timohaha** [comment]
> @timohaha 是不是因为torch版本的问题，我是1.4.0

可能是这个原因，我服务器torch装的是1.1.0
