### ISSUE TITLE
pytorch 和torchvision 版本

### ISSUE THREAD

**Issue by TianyouChen** [ouyanghuiyu/yolo-face-with-landmark#3]
你好，pytorch 和torchvision 版本是多少呢，我训练报下面的错
TypeError: _resolve_type_from_object(): incompatible function arguments. The following argument types are supported:
    1. (arg0: object, arg1: torch._C._jit_tree_views.SourceRange, arg2: Callable[[str], function]) -> torch._C.Type

Invoked with: typing.Union[int, NoneType], None, <function try_ann_to_type.<locals>.fake_rcb at 0x7f52e2a0de18>
谷歌搜了一下说是版本问题

**Comment by DayBreak-u** [comment]
@TianyouChen 更新了requirements.txt

**Comment by TianyouChen** [comment]
> @TianyouChen 更新了requirements.txt

好的 谢谢
